language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in chrome-extension-key.pem.enc -out ~/chrome-extension-key.pem -d
before_deploy:
- export TRAVIS_TAG=$(git describe)
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 'dist/chromeipass.crx'
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
notifications:
  email: false
if: tag IS false
