language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in chrome-extension-key.pem.enc -out ~/chrome-extension-key.pem -d
before_deploy:
- export TRAVIS_TAG=$(git describe)
- git tag -f $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 'dist/chromeipass.crx'
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
after_deploy:
- ./xml.js
- export TRAVIS_TAG=update-${TRAVIS_BRANCH}
- git tag -f $TRAVIS_TAG
- dpl --provider=releases --api-key=$GITHUB_TOKEN --file=update.xml --overwrite=true
notifications:
  email: false
if: tag IS false
