language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
  -in chrome-extension-key.pem.enc -out ~/chrome-extension-key.pem -d
before_deploy:
- echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
- export GIT_TAG=$(git describe)
- git tag ${GIT_TAG}
- git push -f origin ${GIT_TAG}
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/*
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  email: false
